apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: abc.tls
secretDescriptor:
  backendType: secretsManager
  type: kubernetes.io/tls
  data:
    - key: abc.crt
      name: tls.crt
    - key: abc.key
      name: tls.key
  compressed: true